import type { EventoSanitario } from './types'

export const MOCK_EVENTOS: EventoSanitario[] = [
  {
    id: '1',
    animalId: 'GV-001',
    tipo: 'vacuna',
    fecha: '2024-03-15',
    descripcion: 'Vacunación antiaftosa anual. Dosis aplicada correctamente.',
    estado: 'recuperado',
    veterinario: 'Dr. Martínez',
    tratamientoCerrado: true,
  },
  {
    id: '2',
    animalId: 'GV-001',
    tipo: 'enfermedad',
    fecha: '2024-04-02',
    descripcion: 'Síntomas de mastitis subclínica detectados. Inflamación leve en cuarto posterior derecho.',
    estado: 'en_tratamiento',
    veterinario: 'Dr. Martínez',
    tratamientoCerrado: false,
  },
  {
    id: '3',
    animalId: 'GV-001',
    tipo: 'tratamiento',
    fecha: '2024-04-03',
    descripcion: 'Inicio de tratamiento con antibiótico. Amoxicilina 15mg/kg durante 5 días.',
    estado: 'en_tratamiento',
    medicamento: 'Amoxicilina 15mg/kg',
    veterinario: 'Dr. Martínez',
    tratamientoCerrado: false,
  },
  {
    id: '4',
    animalId: 'GV-001',
    tipo: 'vacuna',
    fecha: '2024-01-10',
    descripcion: 'Vacuna contra brucelosis. Cepa 19 aplicada.',
    estado: 'recuperado',
    veterinario: 'Dra. Rodríguez',
    tratamientoCerrado: true,
  },
  {
    id: '5',
    animalId: 'GV-001',
    tipo: 'enfermedad',
    fecha: '2023-11-20',
    descripcion: 'Cojera leve en pata delantera izquierda. Posible dermatitis interdigital.',
    estado: 'recuperado',
    veterinario: 'Dr. Martínez',
    tratamientoCerrado: true,
  },
]
